
- name: install Net_URL_Mapper
  pear: name=Net_URL_Mapper-beta
        state=latest

- name: install latest version of git
  yum: name=git
       state=latest

- name: add httpd routing config
  template: src=httpd.conf.j2
            dest=/etc/httpd/conf.d/{{ appname }}.conf
            mode=0755

- name: restart apache server
  become: yes
  command: systemctl restart httpd

- name: send config for develop
  copy: src=./files/conf/webpack
        dest={{ prjpath }}/conf

- name: send source directory
  copy: src=./files/src
        dest={{ prjpath }}/

- name: install tetraring
  git: repo=https://github.com/simpart/tetraring4php.git
       dest={{ prjpath }}/src/php/ttr version=master

- name: create source inner directory (ctrl)
  file: path={{ prjpath }}/src/js/ctrl/init
        state=directory

- name: create source inner directory (conf)
  file: path={{ prjpath }}/src/js/conf
        state=directory

- name: create source inner directory (dist)
  file: path={{ prjpath }}/src/js/dist
        state=directory

- name: create source inner directory (dist)
  file: path={{ prjpath }}/src/php/define
        state=directory

- name: send js source template (login)
  template: src=src/js/ctrl/init/login.js.j2
            dest={{ prjpath }}/src/js/ctrl/init/login.js
            mode=0755

- name: send php source template (common define)
  template: src=src/php/define/common.php.j2
            dest={{ prjpath }}/src/php/define/common.php
            mode=0755

- name: send index file
  copy: src=./files/index.php
        dest={{ prjpath }}

- name: delete index html file
  file: path={{ prjpath }}/index.html
        state=absent

- name: send build tool
  copy: src=./files/tool/build.sh
        mode=0755
        dest={{ prjpath }}/tool

- name: install mofron modules
  command: npm install --save-dev mofron-tmpl-login chdir={{ prjpath }}

- name: execute build appfront
  command: ./build.sh chdir={{ prjpath }}/tool


